config/routes.rb
Rails.application.routes.draw do
  
  resources :paragraphs
  resources :change_user_type_requests
  resources :book_requests
  
  resources :creating_meeting_place_requests
  
  root 'main#index'
  get 'main/abouts_us'

  #writes
  post '/follow/:id', :to => 'paragraphs#follow' , as: "follow"
  post '/unfollow/:id', :to => 'paragraphs#unfollow', as: "unfollow"


  #paragraphs
  get 'writers_paragraphs', :to => 'paragraphs#writers_paragraphs'
  get 'followed_writers_paragraphs', :to => 'paragraphs#followed_writers_paragraphs'

  #error routes
  match "/404", to: "errors#page_not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  #Books Routes
  get 'library', :to => 'books#index'
  get 'exchange_library', :to => 'books#exchange_library'
  get 'check_requests', :to => 'book_requests#arrived_book_request', :as => "show_request"
  post 'accepted_request', :to => 'book_requests#accept_meeting', :as => "accepted_meeting"
  get 'rejected_request', :to => 'book_requests#reject_meeting', :as => "rejected_meeting"
  get 'requests_archive', :to => 'book_requests#requests_archive', :as => "requests_archive"
  get 'presence/update'
  


  resources :books, :except => [:index, :delete] do
    collection do
      post :search
      post :add_book_to_user
      get :add_book_to_database
      delete :remove_book_from_user
    end
  end

  #Devise Routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :meeting_place do
    get '/meeting_places/sign_out' => 'devise/sessions#destroy'
    get '/meeting_places/index' => 'meeting_places#Main'
    patch '/meeting_places/presence/updateFirstSide', to: 'presence#updateFirstSide'
    patch '/meeting_places/presence/updateSecondSide', to: 'presence#updateSecondSide'

  end

  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
    get '/admin/dashboard' => 'admin_actions#dashboard'
    get '/admin/user_list' => 'admin_actions#user_list'

    get '/admin/meeting_place_requests' => 'admin_actions#meeting_place_request_list', as: "admin_MPR"
    get '/admin/change_user_type_requests' => 'admin_actions#change_user_type_requests', as: "admin_CUTR"

    post '/admin/ban/:id', to: 'admin_actions#ban_user', as: 'lock_user'
    post '/admin/unban/:id', to: 'admin_actions#unban_user', as: 'unlock_user'

    post '/admin/createMP/:id', to: 'admin_actions#create_meeting_place_profile', as: 'CreateMP'
    post '/admin/changeUT/:id', to: 'admin_actions#change_user_type', as: 'changeUT'

    post '/admin/rejectMP/:id', to: 'admin_actions#reject_meeting_request', as: 'rejectMP'
    post '/admin/rejectUT/:id', to: 'admin_actions#reject_user_request', as: 'rejectUT'
  end
  # authenticated :meeting_place do
  #   root to: "home#index"
  # end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_for :meeting_place, controllers: {
    sessions: 'meeting_place/sessions'
  }
end

app/models/creating_meeting_place_request.rb
class CreatingMeetingPlaceRequest < ApplicationRecord
    belongs_to :supported_governate, foreign_key: :governate, class_name: 'SupportedGovernate'
    has_one_attached :contract
end

app/controllers/creating_meeting_place_requests_controller.rb
class CreatingMeetingPlaceRequestsController < ApplicationController
  before_action :set_creating_meeting_place_request, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: [:show, :index]

  def index
    @creating_meeting_place_requests = CreatingMeetingPlaceRequest.all
  end

  def show
  end

  def new
    @disable_nav = true
    @creating_meeting_place_request = CreatingMeetingPlaceRequest.new
  end

  def edit
  end

  def create
    @creating_meeting_place_request = CreatingMeetingPlaceRequest.new(creating_meeting_place_request_params)
    
    respond_to do |format|
      if @creating_meeting_place_request.save
        format.html { redirect_to root_path, notice: "تم ارسال طلبك لتتم معالجته، سيتم أشعارك على البريد الالكتروني بحالة الطلب" }
        format.json { render :show, status: :created, location: @creating_meeting_place_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creating_meeting_place_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @creating_meeting_place_request.update(creating_meeting_place_request_params)
        format.html { redirect_to creating_meeting_place_request_url(@creating_meeting_place_request), notice: "Creating meeting place request was successfully updated." }
        format.json { render :show, status: :ok, location: @creating_meeting_place_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creating_meeting_place_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @creating_meeting_place_request.destroy

    respond_to do |format|
      format.html { redirect_to creating_meeting_place_requests_url, notice: "Creating meeting place request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_creating_meeting_place_request
      @creating_meeting_place_request = CreatingMeetingPlaceRequest.find(params[:id])
    end

    def creating_meeting_place_request_params
      params.require(:creating_meeting_place_request).permit(:email, :stor_name, :owner_name, :contract, :city_name, :location_details, :governate)
    end
end

app/helpers/creating_meeting_place_requests_helper.rb
module CreatingMeetingPlaceRequestsHelper
end

app/views/creating_meeting_place_requests/_creating_meeting_place_request.html.erb
<div id="<%= dom_id creating_meeting_place_request %>">
  <p>
    <strong>Email:</strong>
    <%= creating_meeting_place_request.email %>
  </p>
  <p>
    <strong>Stor name:</strong>
    <%= creating_meeting_place_request.stor_name %>
  </p>
  <p>
    <strong>Owner name:</strong>
    <%= creating_meeting_place_request.owner_name %>
  </p>
  <% if creating_meeting_place_request.contract.attached? %>
    <p>
      <strong>Contrac image:</strong>
      <%= image_tag(creating_meeting_place_request.contract, style:"width: 150px;") %>
    </p>
  <% end %>
  <p>
    <strong>governate:</strong>
    <%= creating_meeting_place_request.supported_governate.name %>
  </p>
  <p>
    <strong>City name:</strong>
    <%= creating_meeting_place_request.city_name %>
  </p>
  <p>
    <strong>Location details:</strong>
    <%= creating_meeting_place_request.location_details %>
  </p>
</div>

app/views/creating_meeting_place_requests/_form.html.erb
 <%= stylesheet_link_tag "account"%>
<div class="container-fluid">
  <div class="row justify-content-center align-items-center" style="height: 100vh;">
    <div class="mx-auto center-form col-md-6">
      <%= form_with(model: creating_meeting_place_request) do |form| %>
        <h2>طلب إنشاء ملتقى</h2>
        <% if creating_meeting_place_request.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(creating_meeting_place_request.errors.count, "error") %> prohibited this creating_meeting_place_request from being saved:</h2>
            <ul>
              <% creating_meeting_place_request.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div  class="form-group email">
          <%= form.label :"البريد الإلكتروني" %>
          <%= form.text_field :email %>
        </div>
        <div class="form-group" >
          <%= form.label :"اسم المحل التجاري" %>
          <%= form.text_field :stor_name %>
        </div>
        <div class="form-group fullname">
          <%= form.label :"اسم المالك الثلاثي" %>
          <%= form.text_field :owner_name %>
        </div>
        <div class="form-group contract">
          <%= form.label :"صورة عقد المحل التجاري"%>
          <%= form.file_field :contract, style: "border: 0px"%>
        </div >
        <div class="form-group">
          <%= form.label :"محافظتك" %>
          <%= form.collection_select(:governate, SupportedGovernate.all, :id, :name) %>
        </div>
        <div class="form-group city">
          <%= form.label :"اسم المدينة" %>
          <%= form.text_field :city_name %>
        </div>
        <div class="form-group location-details">
          <%= form.label :"تفاصيل المكان" %>
          <%= form.text_field :location_details %>
        </div>
        <div class="form-group submit-btn">
          <%= form.submit "أرسل الطلب" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= javascript_include_tag('meeting_requests.js') %>

app/views/creating_meeting_place_requests/edit.html.erb
<h1>Editing creating meeting place request</h1>

<%= render "form", creating_meeting_place_request: @creating_meeting_place_request %>

<br>

<div>
  <%= link_to "Show this creating meeting place request", @creating_meeting_place_request %> |
  <%= link_to "Back to creating meeting place requests", creating_meeting_place_requests_path %>
</div>

app/views/creating_meeting_place_requests/index.html.erb
<p style="color: green"><%= notice %></p>
<h1></h1>
<div id="creating_meeting_place_requests">
  <% @creating_meeting_place_requests.each do |creating_meeting_place_request| %>
    <%= render creating_meeting_place_request %>
    <p>
      <%= link_to "Show this creating meeting place request", creating_meeting_place_request %>
    </p>
  <% end %>
</div>
<%= link_to "New creating meeting place request", new_creating_meeting_place_request_path %>

app/views/creating_meeting_place_requests/new.html.erb
<%= render "form", creating_meeting_place_request: @creating_meeting_place_request %>

app/views/creating_meeting_place_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @creating_meeting_place_request %>

<div>
  <%= link_to "Edit this creating meeting place request", edit_creating_meeting_place_request_path(@creating_meeting_place_request) %> |
  <%= link_to "Back to creating meeting place requests", creating_meeting_place_requests_path %>

  <%= button_to "Destroy this creating meeting place request", @creating_meeting_place_request, method: :delete %>
</div>