config/routes.rb
Rails.application.routes.draw do
  
  resources :paragraphs
  resources :change_user_type_requests
  resources :book_requests
  
  resources :creating_meeting_place_requests
  
  root 'main#index'
  get 'main/abouts_us'

  #writes
  post '/follow/:id', :to => 'paragraphs#follow' , as: "follow"
  post '/unfollow/:id', :to => 'paragraphs#unfollow', as: "unfollow"


  #paragraphs
  get 'writers_paragraphs', :to => 'paragraphs#writers_paragraphs'
  get 'followed_writers_paragraphs', :to => 'paragraphs#followed_writers_paragraphs'

  #error routes
  match "/404", to: "errors#page_not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  #Books Routes
  get 'library', :to => 'books#index'
  get 'exchange_library', :to => 'books#exchange_library'
  get 'check_requests', :to => 'book_requests#arrived_book_request', :as => "show_request"
  post 'accepted_request', :to => 'book_requests#accept_meeting', :as => "accepted_meeting"
  get 'rejected_request', :to => 'book_requests#reject_meeting', :as => "rejected_meeting"
  get 'requests_archive', :to => 'book_requests#requests_archive', :as => "requests_archive"
  get 'presence/update'
  


  resources :books, :except => [:index, :delete] do
    collection do
      post :search
      post :add_book_to_user
      get :add_book_to_database
      delete :remove_book_from_user
    end
  end

  #Devise Routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :meeting_place do
    get '/meeting_places/sign_out' => 'devise/sessions#destroy'
    get '/meeting_places/index' => 'meeting_places#Main'
    patch '/meeting_places/presence/updateFirstSide', to: 'presence#updateFirstSide'
    patch '/meeting_places/presence/updateSecondSide', to: 'presence#updateSecondSide'

  end

  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
    get '/admin/dashboard' => 'admin_actions#dashboard'
    get '/admin/user_list' => 'admin_actions#user_list'

    get '/admin/meeting_place_requests' => 'admin_actions#meeting_place_request_list', as: "admin_MPR"
    get '/admin/change_user_type_requests' => 'admin_actions#change_user_type_requests', as: "admin_CUTR"

    post '/admin/ban/:id', to: 'admin_actions#ban_user', as: 'lock_user'
    post '/admin/unban/:id', to: 'admin_actions#unban_user', as: 'unlock_user'

    post '/admin/createMP/:id', to: 'admin_actions#create_meeting_place_profile', as: 'CreateMP'
    post '/admin/changeUT/:id', to: 'admin_actions#change_user_type', as: 'changeUT'

    post '/admin/rejectMP/:id', to: 'admin_actions#reject_meeting_request', as: 'rejectMP'
    post '/admin/rejectUT/:id', to: 'admin_actions#reject_user_request', as: 'rejectUT'
  end
  # authenticated :meeting_place do
  #   root to: "home#index"
  # end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_for :meeting_place, controllers: {
    sessions: 'meeting_place/sessions'
  }
end

app/views/partial/_adminSideBar.html.erb
<div class="col-12 col-sm-3 col-xl-2 px-sm-2 px-0 bg-dark d-flex sticky-top vh-100">
  <div class="d-flex flex-sm-column flex-row flex-grow-1 align-items-center align-items-sm-start px-3 pt-2 text-white">
    <a href="/" class="d-flex align-items-center pb-sm-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <span class="fs-5"><span class="d-none d-sm-inline">لوحة التحكم</span></span>
    </a>
    <ul class="nav nav-pills flex-sm-column flex-row flex-nowrap flex-shrink-1 flex-sm-grow-0 flex-grow-1 mb-sm-auto mb-0 justify-content-center align-items-center align-items-sm-start" id="menu">
      <li class="nav-item">
        <%= link_to(root_path, class: "nav-link px-sm-0 px-2") do %>
          <%= content_tag(:i, "", class: "fs-5 bi-house-fill") %>
          <span class="ms-1 d-none d-sm-inline">الرئيسية</span>
        <% end %>
      </li>
      <li>
        <%= link_to(admin_user_list_path, class: "nav-link px-sm-0 px-2") do %>
          <%= content_tag(:i, "", class: "fs-5 bi-person-vcard-fill") %>
          <span class="ms-1 d-none d-sm-inline">بيانات المستخدمين</span>
        <% end %>
      </li>
      <li class="dropdown">
        <a href="#" class="nav-link dropdown-toggle px-sm-0 px-1" id="dropdown" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="fs-5 bi-paperclip"></i><span class="ms-1 d-none d-sm-inline">الطلبات</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-med shadow" aria-labelledby="dropdown">
          <li>
            <%= link_to(admin_MPR_path, class: "dropdown-item") do %>
              <%= content_tag(:i, "", class: "fs-5 bi-shop") %>
              <span class="ms-1 d-none d-sm-inline">طلبات إنشاء الملتقى</span>
            <% end %>
          </li>
          <li>
            <%= link_to(admin_CUTR_path	, class: "dropdown-item") do %>
              <%= content_tag(:i, "", class: "fs-5 bi-pen-fill") %>
              <span class="ms-1 d-none d-sm-inline">طلبات ترقية كاتب</span>
            <% end %>
          </li>
        </ul>
      </li>
    </ul>
    <div class="dropdown py-sm-4 mt-sm-auto ms-auto ms-sm-0 flex-shrink-1">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="fs-5 bi-gear-fill"></i>
        <span class="d-none d-sm-inline mx-1">الإعدادات</span>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><%= link_to "تغيير كلمة السر", edit_admin_registration_path ,class: "dropdown-item" %></li>
        <li>
          <hr class="dropdown-divider">
        </li>
        <li><%= link_to "تسجيل الخروج", destroy_admin_session_path ,class: "dropdown-item" %></li>
      </ul>
    </div>
  </div>
</div>

app/views/partial/_footer.html.erb
<%= stylesheet_link_tag "footer"%>
<div class="footer-container">
  <section class="contact-section" id="section_5">
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path
                        fill="#36363e" fill-opacity="1"
                        d="M0,96L40,117.3C80,139,160,181,240,186.7C320,192,400,160,480,149.3C560,139,640,149,720,176C800,203,880,245,960,250.7C1040,256,1120,224,1200,229.3C1280,235,1360,277,1400,298.7L1440,320L1440,320L1400,320C1360,320,1280,320,1200,320C1120,320,1040,320,960,320C880,320,800,320,720,320C640,320,560,320,480,320C400,320,320,320,240,320C160,320,80,320,40,320L0,320Z"></path></svg>
  </section>
  <footer class="site-footer section-padding">
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-5 col-12 mb-3">
          <h6><%= link_to "سبيل", root_path, class: "custom-link mb-1" %></h6>
          <% if user_signed_in? and !current_user.writer? %>
            <li><%= link_to "طلب الترقية إلى كاتب", new_change_user_type_request_path %></li>
          <% end %>
          <% unless current_user %>
            <li><%= link_to "مدير النظام", new_admin_session_path %></li>
          <% end %>
        </div>
        <div class="col-lg-3 col-md-3 col-12 ms-lg-auto mb-3">
          <h6 class="text-white mb-3">الموقع</h6>
          <p class="text-white mt-2">
            <i class="bi-geo-alt"></i>
            سوريا
          </p>
        </div>
        <div class="col-lg-3 col-md-4 col-12 mb-3">
          <h6 class="text-white mb-3">معلومات الاتصال</h6>
          <p class="text-white mb-1">
            <i class="bi-telephone me-1"></i>
            <a href="tel: 090-080-0760" class="text-white">
              090-080-0760
            </a>
          </p>
          <p class="text-white mb-0">
            <i class="bi-envelope me-1"></i>
            <a href="mailto:info@company.com" class="text-white">
              Sabeel@example.com
            </a>
          </p>
        </div>
        <div
                        class="col-lg-6 col-md-7 copyright-text-wrap col-12 d-flex flex-wrap align-items-center mt-4 ms-auto">
          <p class="copyright-text mb-0 me-4">Copyright © sabeel
          </p>
          <ul class="social-icon">
            <li class="social-icon-item">
              <a href="#"
              class="social-icon-link social-icon-facebook bi-facebook"></a>
            </li>
            <li class="social-icon-item">
              <a href="#"
              class="social-icon-link social-icon-instagram bi-instagram"></a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
</div>

app/views/partial/_navbar.html.erb
<%= stylesheet_link_tag "navbar"%>
<nav class="navbar navbar-expand-lg bg-light fixed-top shadow-lg">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag("logo.png", style: "width:60px; height:60px;") %>
      سبيل
    </a>
    <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link click-scroll" href="#section_1">الصفحة
            الرئيسية</a>
        </li>
        <li class="nav-item">
          <a class="nav-link click-scroll" href="#section_2">حول</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle click-scroll"
                                href="#section_3"
                                id="navbarLightDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">الحساب</a>
          <ul class="dropdown-menu dropdown-menu-light"
                                aria-labelledby="navbarLightDropdownMenuLink">
            <li>
              <%= link_to "تسجيل دخول", new_user_session_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "إنشاء حساب", new_user_registration_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link click-scroll" href="#section_4">الملتقى</a>
        </li>
        <li class="nav-item">
          <a class="nav-link click-scroll" href="#section_5">اتصل
            بنا</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partial/_notice.html.erb
<% if notice %>
  <div id="notice-wraper">
    <p class="alert alert-success"><%= notice  %></p>
  </div>
<% elsif alert %>
  <div id="notice-wraper">
    <p class="alert alert-danger"><%= alert %></p>
  </div>
<% end %>
<script>
  $(document).ready(function(){
      setTimeout(function(){
          $('#notice-wraper').fadeOut("slow", function(){
              $this.remove();
          })
      }, 2000);
  });
</script>

app/views/partial/_userNavbar.html.erb
<%= stylesheet_link_tag "bootstrap.min.css"%>
<%= stylesheet_link_tag "bootstrap-icons.css"%>
<%= stylesheet_link_tag "navbar"%>
<nav class="navbar navbar-expand-lg bg-light fixed-top shadow-lg">
  <div class="container">
    <a class="navbar-brand" href="/">
      <%= image_tag("logo.png", style: "width:60px; height:60px;") %>
      سبيل
    </a>
    <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false"
                    aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%= link_to "مكتبتي", library_path, class: "nav-link" %>
        </li>
        <% if current_user.writer? %>
          <li class="nav-item">
            <%= link_to "صفحتي", paragraphs_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle click-scroll"
                                href="#section_3"
                                id="navbarLightDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">الفقرات</a>
          <ul class="dropdown-menu dropdown-menu-light"
                                aria-labelledby="navbarLightDropdownMenuLink">
            <li class="nav-item">
              <%= link_to "كل الكتّاب", writers_paragraphs_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "الكتّاب المٌتابَعون", followed_writers_paragraphs_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
        <% unless current_user.books.count == 0 %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle click-scroll"
                                href="#section_3"
                                id="navbarLightDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">التبادل</a>
            <ul class="dropdown-menu dropdown-menu-light"
                                aria-labelledby="navbarLightDropdownMenuLink">
              <li>
                <%= link_to "مكتبة التبادل ", exchange_library_path	, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "طلبات التبادل المرسلة", book_requests_path, class: "dropdown-item" %>
              </li>
              <li>
                <%= link_to "أرشيف الطلبات المقبولة", requests_archive_path, class: "dropdown-item" %>
              </li>
            </ul>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle click-scroll"
                                href="#section_3"
                                id="navbarLightDropdownMenuLink" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">حسابي</a>
          <ul class="dropdown-menu dropdown-menu-light"
                                aria-labelledby="navbarLightDropdownMenuLink">
            <li>
              <%= link_to "بياناتي", edit_user_registration_path, class: "dropdown-item" %>
            </li>
            <li>
              <%= link_to "تسجيل خروج", destroy_user_session_path, class: "dropdown-item" %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
</div>
</nav>