config/routes.rb
Rails.application.routes.draw do
  
  resources :paragraphs
  resources :change_user_type_requests
  resources :book_requests
  
  resources :creating_meeting_place_requests
  
  root 'main#index'
  get 'main/abouts_us'

  #writes
  post '/follow/:id', :to => 'paragraphs#follow' , as: "follow"
  post '/unfollow/:id', :to => 'paragraphs#unfollow', as: "unfollow"


  #paragraphs
  get 'writers_paragraphs', :to => 'paragraphs#writers_paragraphs'
  get 'followed_writers_paragraphs', :to => 'paragraphs#followed_writers_paragraphs'

  #error routes
  match "/404", to: "errors#page_not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  
  #Books Routes
  get 'library', :to => 'books#index'
  get 'exchange_library', :to => 'books#exchange_library'
  get 'check_requests', :to => 'book_requests#arrived_book_request', :as => "show_request"
  post 'accepted_request', :to => 'book_requests#accept_meeting', :as => "accepted_meeting"
  get 'rejected_request', :to => 'book_requests#reject_meeting', :as => "rejected_meeting"
  get 'requests_archive', :to => 'book_requests#requests_archive', :as => "requests_archive"
  get 'presence/update'
  


  resources :books, :except => [:index, :delete] do
    collection do
      post :search
      post :add_book_to_user
      get :add_book_to_database
      delete :remove_book_from_user
    end
  end

  #Devise Routes
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'

  }


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  devise_scope :meeting_place do
    get '/meeting_places/sign_out' => 'devise/sessions#destroy'
    get '/meeting_places/index' => 'meeting_places#Main'
    patch '/meeting_places/presence/updateFirstSide', to: 'presence#updateFirstSide'
    patch '/meeting_places/presence/updateSecondSide', to: 'presence#updateSecondSide'

  end

  devise_scope :admin do
    get '/admins/sign_out' => 'devise/sessions#destroy'
    get '/admin/dashboard' => 'admin_actions#dashboard'
    get '/admin/user_list' => 'admin_actions#user_list'

    get '/admin/meeting_place_requests' => 'admin_actions#meeting_place_request_list', as: "admin_MPR"
    get '/admin/change_user_type_requests' => 'admin_actions#change_user_type_requests', as: "admin_CUTR"

    post '/admin/ban/:id', to: 'admin_actions#ban_user', as: 'lock_user'
    post '/admin/unban/:id', to: 'admin_actions#unban_user', as: 'unlock_user'

    post '/admin/createMP/:id', to: 'admin_actions#create_meeting_place_profile', as: 'CreateMP'
    post '/admin/changeUT/:id', to: 'admin_actions#change_user_type', as: 'changeUT'

    post '/admin/rejectMP/:id', to: 'admin_actions#reject_meeting_request', as: 'rejectMP'
    post '/admin/rejectUT/:id', to: 'admin_actions#reject_user_request', as: 'rejectUT'
  end
  # authenticated :meeting_place do
  #   root to: "home#index"
  # end

  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  devise_for :meeting_place, controllers: {
    sessions: 'meeting_place/sessions'
  }
end

app/models/book_request.rb
class BookRequest < ApplicationRecord
  belongs_to :requester_id, class_name: 'User'
  belongs_to :requested_book_id,  class_name: 'UserHaveBook'
  belongs_to :meeting_place_id, class_name: 'MeetingPlace'

  enum state: [:"معلق", :"قبول", :"مرفوض"]
  
  after_initialize :set_default_state, :if => :new_record?
  def set_default_state
    self.state ||= :معلق
  end
end

app/controllers/book_requests_controller.rb
class BookRequestsController < ApplicationController
  before_action :set_book_request, only: %i[ show edit update destroy ]

  def requests_archive
    @requests = RequestLog.where(:first_side_id => current_user.id).or( RequestLog.where(:second_side_id => current_user.id)).order(meeting_time: :desc)
  end

  def index
    @book_requests = BookRequest.select(
      [
        BookRequest.arel_table[Arel.star], Book.arel_table[:title], Book.arel_table[:google_book_picture_tag], MeetingPlace.arel_table[:store_name], MeetingPlace.arel_table[:city_name], MeetingPlace.arel_table[:location_details],  SupportedGovernate.arel_table[:name].as('governate')
      ]
    ).where(BookRequest.arel_table[:requester_id_id].eq(current_user.id)).joins(
      BookRequest.arel_table.join(UserHaveBook.arel_table).on(
        BookRequest.arel_table[:requested_book_id_id].eq(UserHaveBook.arel_table[:id])
      ).join_sources
    ).joins(
      BookRequest.arel_table.join(Book.arel_table).on(
        UserHaveBook.arel_table[:book_id].eq(Book.arel_table[:id])
      ).join_sources
    ).joins(
      BookRequest.arel_table.join(MeetingPlace.arel_table).on(
        BookRequest.arel_table[:meeting_place_id_id].eq(MeetingPlace.arel_table[:id])
      ).join_sources
    ).joins(
      BookRequest.arel_table.join(SupportedGovernate.arel_table).on(
        MeetingPlace.arel_table[:governate].eq(SupportedGovernate.arel_table[:id])
      ).join_sources
    )
    
  end

  def arrived_book_request
    puts params[:book]
    @book = Book.find(params[:book])
    @requested_book_request = BookRequest.select(
      [
        BookRequest.arel_table[Arel.star], MeetingPlace.arel_table[:store_name], MeetingPlace.arel_table[:city_name], MeetingPlace.arel_table[:location_details],  SupportedGovernate.arel_table[:name].as('governate')
      ]
    ).where(requested_book_id_id: params[:user_have_book_id]).joins(
      BookRequest.arel_table.join(UserHaveBook.arel_table).on(
        BookRequest.arel_table[:requested_book_id_id].eq(UserHaveBook.arel_table[:id])
      ).join_sources
    ).joins(
      BookRequest.arel_table.join(MeetingPlace.arel_table).on(
        BookRequest.arel_table[:meeting_place_id_id].eq(MeetingPlace.arel_table[:id])
      ).join_sources
    ).joins(
      BookRequest.arel_table.join(SupportedGovernate.arel_table).on(
        MeetingPlace.arel_table[:governate].eq(SupportedGovernate.arel_table[:id])
      ).join_sources
    )
    
  end

  def show

  end

  def new
    if @book_request
      puts @book_request.errors
    end
    @owner_book = UserHaveBook.find(params[:book])
    @book = Book.find(@owner_book.book_id)
    @book_request = BookRequest.new
  end
  
  def edit
  end


  # book accepting 
  def accept_meeting
    @book_request = BookRequest.find(params[:request_id])
    @second_book = UserHaveBook.find(@book_request.requested_book_id_id.to_s)
    @first_book = UserHaveBook.where(user_id: @book_request.requester_id_id, book_id: params[:first_side_book]).first

    # Log the Meeting 
    @log_request = RequestLog.new
    @log_request.first_side_id = @book_request.requester_id_id
    @log_request.second_side_id = current_user.id
    @log_request.first_side_book_id = params[:first_side_book]
    @log_request.second_side_book_id = @second_book.book_id
    @log_request.meeting_time = @book_request.meeting_time
    @log_request.meeting_place_id = @book_request.meeting_place_id_id
    
    

    puts BookRequest.where(requested_book_id_id: @first_book.id).destroy_all
    puts BookRequest.where(requested_book_id_id: @second_book.id).destroy_all
    
    @first_book.destroy
    @second_book.destroy
    @log_request.save
    

    respond_to do |format|
        format.html { redirect_to library_url, notice: "تم قبول الطلب" }
    end
  end
  
  def reject_meeting
    @book_request = BookRequest.find(params[:book_request_id])
    respond_to do |format|
      if @book_request.update(state: 2)
        format.html { redirect_to root_path, alert: "تم رفض الطلب" }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    @book_request = BookRequest.new(book_request_params)
    @book_request.requester_id_id = current_user.id
    respond_to do |format|
      if @book_request.save
        format.html { redirect_to library_path, notice: "تم إرسال طلبك بنجاح" }
        format.json { render :show, status: :created, location: @book_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book_request.update(book_request_params)
        format.html { redirect_to book_request_url(@book_request), notice: "Book request was successfully updated." }
        format.json { render :show, status: :ok, location: @book_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_request.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book_request.destroy

    respond_to do |format|
      format.html { redirect_to book_requests_url, notice: "تم إلغاء طلبك" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_request
      @book_request = BookRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_request_params
      params.require(:book_request).permit(:requester_id_id ,:requested_book_id_id, :meeting_place_id_id, :meeting_time)
    end
end

app/helpers/book_requests_helper.rb
module BookRequestsHelper
end

app/views/book_requests/_book_request.html.erb
<div id="<%= dom_id book_request %>">
  <p>
    <strong>Requester:</strong>
    <%= book_request.requester_id_id %>
  </p>
  <p>
    <strong>Requested book:</strong>
    <%= book_request.requested_book_id_id %>
  </p>
  <p>
    <strong>Meeting place:</strong>
    <%= book_request.meeting_place_id_id %>
  </p>
  <p>
    <strong>Meeting time:</strong>
    <%= book_request.meeting_time %>
  </p>
</div>

app/views/book_requests/_form.html.erb
<%= stylesheet_link_tag "book-request"%>
<%= stylesheet_link_tag "library"%>
<div class="request-book d-flex justify-content-evenly flex-wrap">
  <div class="request-form">
    <%= form_with(model: book_request) do |form| %>
      <h2>طلب تبادل كتاب</h2>
      <div class="d-flex mb-5 flex-xl-row flex-column justify-content-around align-items-center" >
        <div class="book ">
          <div class="cover">
            <% if !@book.google_book_picture_tag.blank? %>
              <%= image_tag(@book.google_book_picture_tag) %>
            <% else %>
              <p >
                لا يوجد صورة لعرضها
              </p>
              <i class="bi bi-emoji-frown-fill"></i>
            <% end %>
          </div>
          <div class="description">
            <div class="row">
              <p class="title"><%= @book.title %><br>
              </p>
            </div>
          </div>
        </div>
        <div class="book description">
          <h4 class="text-center">وصف الكتاب</h4>
          <hr class="hr hr-blurry" />
          <p class="description">
            <%= @book.discription %>
          </p>
        </div>
      </div>
      <%= form.hidden_field :requested_book_id_id, value: @owner_book.id %>
      <div class="form-group">
        <%= form.label :meeting_place_id_id, "ملتقيات في منطقتك" %>
        <%= form.collection_select(:meeting_place_id_id, MeetingPlace.where(:governate=> current_user.location), :id, :store_name, { include_blank: 'اختر ملتقى' }, required: true ) %>
      </div>
      <div class="form-group">
        <%= form.label :meeting_time, "موعد اللقاء المقترح" %>
        <% minimum_time = (Time.now + 2.hours).strftime('%Y-%m-%dT%H:%M') %>
        <%= form.datetime_field :meeting_time, required: true, min: minimum_time %>
      </div>
      <div>
        <%= form.submit "ارسل الطلب" %>
      </div>
    <% end %>
  </div>
</div>

app/views/book_requests/arrived_book_request.html.erb
<%= stylesheet_link_tag "forms"%>
<%= stylesheet_link_tag "library"%>
<%= stylesheet_link_tag "containers"%>
<div class="page_container d-flex flex-xl-row flex-md-col mx-5 px-5">
  <div class=" ">
    <div class="book read">
      <div class="cover">
        <% if !@book.google_book_picture_tag.blank? %>
          <%= image_tag(@book.google_book_picture_tag) %>
        <% else %>
          <p >
            لا يوجد صورة لعرضها
          </p>
          <i class="bi bi-emoji-frown-fill"></i>
        <% end %>
      </div>
      <div class="description">
        <div class="row">
          <p class="title"><%= @book.title %><br>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="flex-grow-1">
    <div class="table-container d-flex justify-content-evenly flex-wrap">
      <div class="table-responsive rounded ">
        <table class="table text-center align-middle border-black shadow-lg table-bordered table-hover table-striped">
          <thead class="table-dark text-center">
            <tr>
              <th><i class="bi bi-book ps-2"></i>العروض</th>
              <th> <i class="bi bi-geo-alt ps-2"></i>الملتقى المقترح </th>
              <th><i class="bi bi-clock-history ps-2"></i>الوقت المقترح</th>
              <th><i class="bi bi-eye ps-2"></i>الحالة</th>
              <th>إلغاء الطلب</th>
            </tr>
          </thead>
          <tbody id="book_requests">
            <% @requested_book_request.each do |book_request| %>
              <% if book_request.state != "مرفوض" %>
                <tr class="table-warning">
                  <td>
                    <%= form_with(model: @request_log, url: accepted_meeting_path, local: true) do |f| %>
                      <%= f.collection_select(:first_side_book, User.find(book_request.requester_id_id).books ,:id, :title, { include_blank: 'اختر كتاب' }, required: true) %>
                      <%= f.hidden_field :request_id, value: book_request.id %>
                      <%= f.submit "قبول", class: "btn btn-success" %>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <h4><%= book_request.governate %></h4>
                    <h5>المدينة : <%= book_request.city_name %></h5>
                    <h5>المكان : <%= book_request.store_name %></h5>
                    <h6>تفاصيل الموقع : <%= book_request.location_details %></h6>
                    <button class="btn btn-primary" onclick="openGoogleMaps('<%= book_request.city_name %>','<%=book_request.store_name %>')">عرض الموقع في الخرائط (قد يكون خاطئ)</button>
                  </td>
                  <td>
                    <p>
                      <%= book_request.meeting_time.to_date %>
                      <br>
                      <%= book_request.meeting_time.to_fs(:time) %>
                    </p>
                  </td>
                  <td>
                    <%= book_request.state %>
                  </td>
                  <td>
                    <%= link_to "رفض الطلب", rejected_meeting_path(book_request_id: book_request.id), class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/book_requests/edit.html.erb
<h1>Editing book request</h1>

<%= render "form", book_request: @book_request %>

<br>

<div>
  <%= link_to "Show this book request", @book_request %> |
  <%= link_to "Back to book requests", book_requests_path %>
</div>

app/views/book_requests/index.html.erb
<%= stylesheet_link_tag "book-request"%>
<%= stylesheet_link_tag "containers"%>
<div class="table-container d-flex justify-content-evenly flex-wrap">
  <% if !@book_requests.blank? %>
    <div class="table-responsive rounded ">
      <table class="table text-center align-middle border-black shadow-lg table-bordered table-hover table-striped">
        <thead class="table-dark text-center">
          <tr>
            <th><i class="bi bi-book ps-2"></i>الكتاب</th>
            <th> <i class="bi bi-geo-alt ps-2"></i>الملتقى المقترح </th>
            <th><i class="bi bi-clock-history ps-2"></i>الوقت المقترح</th>
            <th><i class="bi bi-eye ps-2"></i>الحالة</th>
            <th>إجراء</th>
          </tr>
        </thead>
        <tbody id="book_requests">
          <% @book_requests.each do |book_request| %>
            <% if book_request.state == 'مرفوض' %>
              <tr id="<%= dom_id book_request %>" class="table-danger">
              <% elsif book_request.state == 'قبول' %>
                <tr id="<%= dom_id book_request %>" class="table-success">
                <% else %>
                  <tr id="<%= dom_id book_request %>" class="table-warning">
                  <% end %>
                  <td>
                    <div class="d-flex flex-xl-row flex-column justify-content-around align-items-center" >
                      <div>
                        <div class="cover d-flex justify-content-center">
                          <% if !book_request.google_book_picture_tag.blank? %>
                            <%= image_tag(book_request.google_book_picture_tag) %>
                          <% else %>
                            <p >
                              لا يوجد صورة لعرضها
                            </p>
                            <i class="bi bi-emoji-frown-fill"></i>
                          <% end %>
                        </div>
                        <div class="description">
                          <div class="row">
                            <p class="title text-center"><%= book_request.title %><br>
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                  <td class="text-center">
                    <h4><%= book_request.governate %></h4>
                    <h5>المدينة : <%= book_request.city_name %></h5>
                    <h5>المكان : <%= book_request.store_name %></h5>
                    <h6>تفاصيل الموقع : <%= book_request.location_details %></h6>
                    <button class="btn btn-primary" onclick="openGoogleMaps('<%= book_request.city_name %>','<%=book_request.store_name %>')">عرض الموقع في الخرائط (قد يكون خاطئ)</button>
                  </td>
                  <td>
                    <p>
                      <%= book_request.meeting_time.to_date %>
                      <br>
                      <%= book_request.meeting_time.to_fs(:time) %>
                    </p>
                  </td>
                  <td>
                    <%= book_request.state %>
                  </td>
                  <td>
                    <%= button_to book_request.state == 'مرفوض'? "حذف الطلب":"إلفاء الطلب", book_request, method: :delete, class: "btn btn-danger" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <div class="empty-library">
          <p class="text-center mt-5">لم تقم بطلب أي كتاب ! اذهب إلى مكتبة التبادل واحصل على البعض</p>
          <%= link_to "مكتبة التبادل", exchange_library_path,method: :get ,class: "btn btn-dark btn-lg"%>
        </div>
      <% end %>
    </div>
    <script>
      function openGoogleMaps(city_name, storeName) {

        var encodedStoreName  = encodeURIComponent(city_name + " " + storeName);
        console.log(city_name + storeName);
          window.open('https://www.google.com/maps/search/?q=' + encodedStoreName, '_blank');
      }
    </script>

app/views/book_requests/new.html.erb
<%= stylesheet_link_tag "forms"%>
<%= stylesheet_link_tag "containers"%>
<%= render "form", book_request: @book_request %>

app/views/book_requests/requests_archive.html.erb
<%= stylesheet_link_tag "book-request"%>
<%= stylesheet_link_tag "containers"%>
<%= stylesheet_link_tag "library"%>
<div class="table-container d-flex justify-content-evenly flex-wrap">
  <% if !@requests.blank? %>
    <div class="table-responsive rounded ">
      <div class="top-bar d-flex justify-content-start flex-grow-1 p-4 flex-column">
        <div class="text-warning">تبادلات قادمة</div>
        <div class="text-success">تبادلات تبادلات ناجحة</div>
        <div class="text-danger">تبادلات لم تتم</div>
      </div>
      <table class="table text-center align-middle border-black shadow-lg table-bordered table-hover table-striped">
        <thead class="table-dark text-center">
          <tr>
            <th><i class="bi bi-book ps-2"></i>الطرف الأول</th>
            <th> <i class="bi bi-geo-alt ps-2"></i>الملتقى</th>
            <th><i class="bi bi-eye ps-2"></i>الطرف الثاني</th>
          </tr>
        </thead>
        <tbody id="book_requests">
          <% @requests.each do |book_request| %>
            <% if book_request.meeting_time < Time.now%>
              <tr id="<%= dom_id book_request %>" class="table-danger">
              <% else %>
                <tr id="<%= dom_id book_request %>" class="table-warning">
                <% end %>
                <td>
                  <div class="d-flex flex-xl-row flex-column justify-content-around align-items-center" >
                    <div class="book read">
                      <div class="cover d-flex justify-content-center">
                        <% if !book_request.first_side_book.google_book_picture_tag.blank? %>
                          <%= image_tag(book_request.first_side_book.google_book_picture_tag) %>
                        <% else %>
                          <p >
                            لا يوجد صورة لعرضها
                          </p>
                          <i class="bi bi-emoji-frown-fill"></i>
                        <% end %>
                      </div>
                      <div class="description">
                        <div class="row">
                          <p class="title text-center"><%= book_request.first_side_book.title %><br>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
                <td class="text-center">
                  <h5>المدينة : <%= book_request.meeting_place.city_name %></h5>
                  <h5>المكان : <%= book_request.meeting_place.store_name %></h5>
                  <h6>تفاصيل الموقع : <%= book_request.meeting_place.location_details %></h6>
                  <button class="btn btn-primary" onclick="openGoogleMaps('<%= book_request.meeting_place.city_name %>','<%= book_request.meeting_place.store_name %>')">عرض الموقع في الخرائط (قد يكون خاطئ)</button>
                  <p>
                    <%= book_request.meeting_time.to_date %>
                    <br>
                    <%= book_request.meeting_time.to_fs(:time) %>
                  </p>
                </td>
                <td>
                  <div class="d-flex flex-xl-row flex-column justify-content-around align-items-center" >
                    <div class="book read">
                      <div class="cover d-flex justify-content-center">
                        <% if !book_request.second_side_book.google_book_picture_tag.blank? %>
                          <%= image_tag(book_request.second_side_book.google_book_picture_tag) %>
                        <% else %>
                          <p >
                            لا يوجد صورة لعرضها
                          </p>
                          <i class="bi bi-emoji-frown-fill"></i>
                        <% end %>
                      </div>
                      <div class="description">
                        <div class="row">
                          <p class="title text-center"><%= book_request.second_side_book.title %><br>
                          </p>
                        </div>
                      </div>
                    </div>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <div class="empty-library">
        <p class="text-center mt-5">لم تقم بأي تبادل بعد، قم بطلب الكتب من مكتبة التبادل</p>
        <%= link_to "مكتبة التبادل", exchange_library_path,method: :get ,class: "btn btn-dark btn-lg"%>
      </div>
    <% end %>
  </div>
  <script>
    function openGoogleMaps(city_name, storeName) {

      var encodedStoreName  = encodeURIComponent(city_name + " " + storeName);
      console.log(city_name + storeName);
        window.open('https://www.google.com/maps/search/?q=' + encodedStoreName, '_blank');
    }
  </script>

app/views/book_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_request %>

<div>
  <%= link_to "Edit this book request", edit_book_request_path(@book_request) %> |
  <%= link_to "Back to book requests", book_requests_path %>

  <%= button_to "Destroy this book request", @book_request, method: :delete %>
</div>